# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    category:
        label: djetson.shop::lang.filter.category
        modelClass: Djetson\Shop\Models\Category
        nameFrom: name
        conditions: category_id in (:filtered)

    manufacturers:
        label: djetson.shop::lang.filter.manufacturers
        modelClass: Djetson\Shop\Models\Manufacturer
        nameFrom: name
        conditions: manufacturer_id in (:filtered)

    is_active:
        label: djetson.store::lang.filter.is_active
        type: checkbox
        conditions: is_active = true