# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: djetson.shop::lang.order_statuses.label

# Model Form Field configuration
form: $/djetson/shop/models/orderstatus/fields.yaml

# Model Class name
modelClass: Djetson\Shop\Models\OrderStatus

# Default redirect location
defaultRedirect: djetson/shop/orderstatuses

# Create page
create:
    title: djetson.shop::lang.order_statuses.create
    redirect: djetson/shop/orderstatuses/update/:id
    redirectClose: djetson/shop/orderstatuses

# Update page
update:
    title: djetson.shop::lang.order_statuses.update
    redirect: djetson/shop/orderstatuses
    redirectClose: djetson/shop/orderstatuses

# Preview page
preview:
    title: djetson.shop::lang.order_statuses.preview
