items:
    deferredBinding: true
    label: djetson.shop::lang.order_items.label
    view:
        toolbarButtons: create
        toolbarPartial: relations/items_toolbar
        list: $/djetson/shop/models/orderitem/columns.yaml
    manage:
        form: $/djetson/shop/models/orderitem/fields.yaml